### ISSUE TITLE
Remove math tools palette customization step for students

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1092]
When students create a problem set, the math tools customization modal should not be displayed.  This is a confusing step for most users and unnecessary for students at this time.  Future changes will address the need for students to customize their math tools.

The palette remains for teachers/parents/unauthenticated users.

**Comment by abaranowska1** [comment]
@rupeshparab 
When students create a problem set, the math tools customization modal should not be displayed and it works when I click "Create a problem set" button on the dashboard, but when I want to create a problem set using another option ( Create a problem set from the Help option - after click the "?" button ) choosing pallets window is displayed for students. Plz look at this issue 
Gif : 
![student](https://user-images.githubusercontent.com/61964176/80363777-fffc3200-8884-11ea-9305-4218ae24c35e.gif)

**Comment by rupeshparab** [comment]
@abaranowska1 
I have pushed a fix for this, now the modal will not open for students when new problem set page is opened in a new tab

**Comment by abaranowska1** [comment]
@rupeshparab 
The issue still exists after I clicked "Create a problem set " from the Help option - after click the "?" button. 
Steps: 
1. Log in to MathShare via Google as Student
2. Click Create a Problem Set button on the dashboard
3. Click "?" button in the right upper corner 
4. Click Create a Problem Set from this drop-down menu 

**Actual result:** Choosing pallets window is still displayed for students.

![Peek 2020-04-28 09-46](https://user-images.githubusercontent.com/61964176/80461186-30030e00-8935-11ea-85dd-dbd12cf94cc2.gif)


**Tested on:** 
- QA instance
- Google Chrome Version 81.0.4044.92,
- Firefox Browser 75.0
- Ubuntu 16.04

**Comment by rupeshparab** [comment]
There seems to be some issue because of which it is working locally but not in QA env, I am investigating it

**Comment by rupeshparab** [comment]
@abaranowska1 
I have fixed it in the QA env, please check if it is working for you.

**Comment by abaranowska1** [comment]
@rupeshparab 
Thanks, now it is working fine. Math tools palette customization step was removed for students.
