### ISSUE TITLE
Unable to Load Problem Set

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1544]
"Our SME wrote 3 problems in the Set called 9.1.2 (3). We can no longer get that set to load. We have both tried and this is what we see:

**Comment by johnhbenetech** [comment]
@alexrcabral any chance we can grab a URL if they have it (right click the row and copy link)

**Comment by alexrcabral** [comment]
Sure thing, asked for copy of link as well as browser / OS and I'll let you know.

**Comment by alexrcabral** [comment]
@johnhbenetech Link to Set: https://mathshare.benetech.org/#/app/problemSet/edit/CYI3354M4FQ3S

also added info in the top-level issue

**Comment by alexrcabral** [comment]
I've got more links to problem sets which have surfaced the same issue:

- https://mathshare.benetech.org/#/app/problemSet/edit/I5LJEICAR3WZU
- https://mathshare.benetech.org/#/app/problemSet/edit/EUHSRNAWWUWNM
- https://mathshare.benetech.org/#/app/problemSet/edit/EBZ72GQFEAFPM

As for set creation, these are very recently created sets: one was for sure on 11-27 based on the title, the others he believes to have created on Saturday 11/28 or Sunday 11/29.

**Comment by rupeshparab** [comment]
I have merged its fix in QA env and raised PR for prod: https://github.com/benetech/MathShareBackend/pull/101

**Comment by abaranowska1** [comment]
@rupeshparab Should errors still appear in the links from the description? ( links from prod )

**Comment by rupeshparab** [comment]
yes @abaranowska1 , those links are of production, they will have the error as the Prod PR hasn't been merged
https://github.com/benetech/MathShareBackend/pull/101

**Comment by johnhbenetech** [comment]
merged and confirmed working
