### ISSUE TITLE
footer benetech logo stretched

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#654]

**Comment by benetechMatt** [comment]
![image](https://user-images.githubusercontent.com/49413678/60988232-c7e12e00-a308-11e9-8cad-dd108b99adb7.png)

**Comment by benetechMatt** [comment]
Chrome on Mac, chrome on pixel 2

**Comment by benetechMatt** [comment]
resolved on my computer when I updated chrome and cleared cache

**Comment by johnhbenetech** [comment]
@alexrcabral can you still reproduce?

It's harder to clear cache on mobile but let me know (try viewing it in incognito)

**Comment by alexrcabral** [comment]
@johnhbenetech yep, can still reproduce on mathshare-qa while viewing incognito in chrome on pixel 2
