### ISSUE TITLE
Have homepage scroll slowly end on mobile

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#716]
currently the homepage stops immediately when you stop scrolling on mobile.  it should slowly glide to stop like on desktop and most websites do on mobile

**Comment by alexrcabral** [comment]
What phone/OS/browser combo is this on? It's working fine on my phone right now, and I'm running Chrome browser on Pixel 2 (Android).

**Comment by alexrcabral** [comment]
Answer: iPhone / iOS 12.4 / Chrome

**Comment by rupeshparab** [comment]
I have pushed a fix for inertial scroll on Chrome in iOS, can you please check if it is working on your device?

**Comment by johnhbenetech** [comment]
Matt is reporting there is still an issue
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12927553/63611835-6e744c00-c5a2-11e9-91b9-2c25135b5acf.gif)

**Comment by johnhbenetech** [comment]
@benetechMatt can you test this on QA?

**Comment by benetechMatt** [comment]
issue seems to be resolved on live site using chrome on ios
